---
- name: Create new image script
  template:
    src: new_images.sh.j2
    dest: "{{ docker_project_dir }}/new_images.sh"
    owner: root
    group: root
    mode: '0755'

- name: Set up cron job for backup
  cron:
    name: "backup docker containers"
    minute: "0"
    hour: "4"
    weekday: "0"  # Запуск по воскресеньям
    job: "{{ docker_project_dir }}/new_image.sh > /tmp/new_image.log 2>&1"
    state: present
