---
- name: add docker gpg apt Key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_lsb['id'] | lower }}/gpg"
    state: present

- name: add docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_lsb['id'] | lower }} {{ ansible_lsb['codename'] | lower }} stable"
    state: present

- name: Update apt and install docker
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true
  tags:
    - never
    - docker-server
