---
- name: reload docker
  systemd:
    name: "{{ docker_service }}"
    enabled: yes
    state: reloaded
    daemon_reload: yes
  no_log: true

- name: restart docker
  systemd:
    name: "{{ docker_service }}"
    enabled: yes
    state: restarted
    daemon_reload: yes
  no_log: true
